CC=pmixcc
CFLAGS=
LDFLAGS=
RM=rm

default: ipv4_bc_use_case

ipv4_bc_use_case: ipv4_bc_use_case.c
	$(CC) $(CFLAGS) $(LDFLAGS) ipv4_bc_use_case.c -o ipv4_bc_use_case

clean:
	$(RM) -f ipv4_bc_use_case
